indicators:
  - key: "S_IND_004"
    description: "Visits conducted in the current month"
    indicatorQuery: " select count(base_entity_id) from visits where visit_date >= (strftime('%s', date('now', 'start of month'))*1000) "

  - key: "S_IND_003"
    description: "Visits conducted in the last month"
    indicatorQuery: " select count(base_entity_id) from visits where visit_date >= (strftime('%s', date('now', 'start of month', '-1 months'))*1000) "

  - key: "S_IND_001"
    description: "Registration in the last Month"
    indicatorQuery: " select count(distinct baseEntityId) from event where eventType in ('Child Registration',
                      'Adolescent Registration', 'Family Member Registration') and date(eventDate) >= date('now', '-2 month') "

  - key: "S_IND_002"
    description: "Registration in the current month"
    indicatorQuery: " select count(distinct baseEntityId) from event where eventType in ('Child Registration',
                      'Adolescent Registration', 'Family Member Registration') and date(eventDate) >= date('now', '-1 month') "