indicators:
  - key: "LAST_MONTH_VISITS"
    description: "Visits conducted in the last 2 months"
    indicatorQuery: " select count(*) from visits where STRFTIME('%Y-%m-%d', datetime(visit_date/1000,'unixepoch')) >= date('now', '-2 months') "

  - key: "CURR_MONTH_VISITS"
    description: "Visits conducted in the last month"
    indicatorQuery: " select count(*) from visits where STRFTIME('%Y-%m-%d', datetime(visit_date/1000,'unixepoch')) >= date('now', '-1 months') "

  - key: "LAST_MONTH_REG"
    description: "Registrations done in the last month"
    indicatorQuery: "select count(distinct baseEntityId) from event where eventType in ('Child Registration', 'Adolescent Registration', 'Family Member Registration') and date(eventDate) >= date('now', '-2 month')"

  - key: "CURR_MONTH_REG"
    description: "Registrations done in the last 30 days"
    indicatorQuery: " select count(distinct baseEntityId) from event where eventType in ('Child Registration', 'Adolescent Registration', 'Family Member Registration') and date(eventDate) >= date('now', '-1 month') "