indicators:
  - key: "S_IND_001"
    description: "Registration in the last Month"
    indicatorQuery: " select count(distinct baseEntityId) from event where eventType in ('Child Registration',
                      'Adolescent Registration', 'Family Member Registration') and date(eventDate) >= date('now', '-2 month') "

  - key: "S_IND_002"
    description: "Registration in the current month"
    indicatorQuery: " select count(distinct baseEntityId) from event where eventType in ('Child Registration',
                      'Adolescent Registration', 'Family Member Registration') and date(eventDate) >= date('now', '-1 month') "