indicators:
  - key: "CHW_001"
    description: "Total U5 children"
    indicatorQuery: "select count(distinct baseEntityId) from event ev inner join ec_child ch where ev.eventType = 'Child Registration' and ch.base_entity_id = ev.baseEntityId
    and ev.eventDate = '%s' and ev.baseEntityId
     in (select distinct ec_child.base_entity_id from ec_child where ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '') and date(ch.dob) > date('now', '-60 month')"

  - key: "CHW_002"
    description: "Children (0-11 months) who died in the last year"
    indicatorQuery: "select count(distinct event.baseEntityId) from event where eventType = 'Remove Child Under 5'
    and eventDate = '%s'
      and event.baseEntityId in (select ec_child.base_entity_id
      from ec_child where date(ec_child.dob) >= date('now', '-11 month') and date(ec_child.dod) >= date('now', '-12 month'))"

  - key: "CHW_003"
    description: "Children (12-59 months) who died in the last year"
    indicatorQuery: "select count(distinct event.baseEntityId) from event where eventType = 'Remove Child Under 5'
    and eventDate = '%s'
       and event.baseEntityId in (select ec_child.base_entity_id
       from ec_child where date(ec_child.dob) >= date('now', '-60 month') and date(ec_child.dob) < date('now', '-11 month') and date(ec_child.dod) >= date('now', '-12 month'))"

  - key: "CHW_004"
    description: "Children (0-59 months) with a birth certificate"
    indicatorQuery: "select count(distinct event.baseEntityId) from event where eventType = 'Birth Certification'
                         and eventDate = '%s'
                          and event.baseEntityId in (select distinct ec_child.base_entity_id from ec_child where ec_child.birth_cert = 'Yes'
                          and date(ec_child.dob) >= date('now', '-60 month') and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '')"

  - key: "CHW_005"
    description: "Children (0-59 months) without a birth certificate"
    indicatorQuery: "select count(distinct event.baseEntityId) from event where eventType = 'Birth Certification'
                         and eventDate = '%s' and event.baseEntityId in (select distinct ec_child.base_entity_id from ec_child where ec_child.birth_cert = 'No'
                          and date(ec_child.dob) >= date('now', '-60 month') and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '')"

  - key: "CHW_006"
    description: "Children (12-59 months) who were dewormed in the last 6 months"
    indicatorQuery: " select count(distinct re.base_entity_id)
                      from recurring_service_types rt
                      inner join recurring_service_records re on re.recurring_service_id = rt._id
                      inner join ec_child ec on ec.base_entity_id = re.base_entity_id and (( ifnull(ec.entry_point,'') <> 'PNC' ) or (ifnull(ec.entry_point,'') = 'PNC' and date(ec.dob, '+28 days') <= date()))
                      inner join ec_family_member ef on ec.base_entity_id = ef.base_entity_id and ef.date_removed is null
                      where rt.type = 'Deworming' and date(ec.dob) between date('now', '-59 month') and date('now', '-12 month')
                      and ifnull(re.value,'yes') = 'yes'
                      and STRFTIME('%Y-%m-%d', datetime(re.date/1000,'unixepoch')) >=date('now', '-6 month') "

  - key: "CHW_007"
    description: "Children (12-59 months) who were not dewormed in the last 6 months"
    indicatorQuery: "select count(distinct ec.base_entity_id)
                     from ec_child ec
                     inner join ec_family_member ef on ec.base_entity_id = ef.base_entity_id and ef.date_removed is null
                     where (( ifnull(ec.entry_point,'') <> 'PNC' ) or (ifnull(ec.entry_point,'') = 'PNC' and date(ec.dob, '+28 days') <= date()))
                     and date(ec.dob) between date('now', '-59 month') and date('now', '-12 month')
                     and ec.base_entity_id not in (
                     	select re.base_entity_id from recurring_service_records re
                     	inner join recurring_service_types rt on re.recurring_service_id = rt._id
                     	where rt.type = 'Deworming' and ifnull(re.value,'yes') = 'yes'
                     	and STRFTIME('%Y-%m-%d', datetime(re.date/1000,'unixepoch')) >=date('now', '-6 month')
                     )"

  - key: "CHW_008"
    description: "Children (6-59 months) who received Vitamin A in the last 6 months"
    indicatorQuery: " select count(distinct re.base_entity_id)
                      from recurring_service_types rt
                      inner join recurring_service_records re on re.recurring_service_id = rt._id
                      inner join ec_child ec on ec.base_entity_id = re.base_entity_id and (( ifnull(ec.entry_point,'') <> 'PNC' ) or (ifnull(ec.entry_point,'') = 'PNC' and date(ec.dob, '+28 days') <= date()))
                      inner join ec_family_member ef on ec.base_entity_id = ef.base_entity_id and ef.date_removed is null
                      where rt.type = 'Vitamin_A' and date(ec.dob) between date('now', '-59 month') and date('now', '-6 month')
                      and ifnull(re.value,'yes') = 'yes'
                      and STRFTIME('%Y-%m-%d', datetime(re.date/1000,'unixepoch')) >=date('now', '-6 month') "

  - key: "CHW_009"
    description: "Children (6-59 months) who did not receive Vitamin A in the last 6 months"
    indicatorQuery: " select count(distinct ec.base_entity_id)
                      from ec_child ec
                      inner join ec_family_member ef on ec.base_entity_id = ef.base_entity_id and ef.date_removed is null
                      where (( ifnull(ec.entry_point,'') <> 'PNC' ) or (ifnull(ec.entry_point,'') = 'PNC' and date(ec.dob, '+28 days')  <= date()))
                      and date(ec.dob) between date('now', '-59 month') and date('now', '-6 month')
                      and ec.base_entity_id not in (
                      	select re.base_entity_id from recurring_service_records re
                      	inner join recurring_service_types rt on re.recurring_service_id = rt._id
                      	where rt.type = 'Vitamin_A' and ifnull(re.value,'yes') = 'yes'
                        and STRFTIME('%Y-%m-%d', datetime(re.date/1000,'unixepoch')) >=date('now', '-6 month')
                      ) "

  - key: "CHW_010"
    description: "Children (0-5 months) exclusively breastfeeding in their most recent home visit"
    indicatorQuery: "select count(DISTINCT ec.base_entity_id)
                     from ec_child ec
                     inner join (
                     	select e.baseEntityId , max(e.eventDate) eventDate
                     	from event e
                     	where e.eventType = 'Child Home Visit'
                     	group by e.baseEntityId
                     ) e on ec.base_entity_id = e.baseEntityId
                     inner join ec_family_member ef on ec.base_entity_id = ef.base_entity_id and ef.date_removed is null
                     inner join (
                     	select re.base_entity_id , STRFTIME('%Y-%m-%d', datetime(max(re.date)/1000,'unixepoch')) last_exclusive_date
                     	from recurring_service_records re
                     	inner join recurring_service_types rt on re.recurring_service_id = rt._id
                     	where rt.type = 'Exclusive_breastfeeding' and ifnull(re.value,'yes') = 'yes'
                     	group by re.base_entity_id
                     ) ex on ex.base_entity_id = e.baseEntityId and SUBSTR(e.eventDate,1,10) between date(ex.last_exclusive_date, '-1 day') and date(ex.last_exclusive_date, '1 day')
                     where (( ifnull(ec.entry_point,'') <> 'PNC' ) or (ifnull(ec.entry_point,'') = 'PNC' and date(ec.dob, '+28 days')  <= date()))
                     and date(ec.dob) between date('now', '-5 month') and date('now')  "

  - key: "CHW_011"
    description: "Children (0-5 months) not exclusively breastfeeding in their most recent home visit"
    indicatorQuery: " select count(ec.base_entity_id)
                      from ec_child ec
                      inner join (
                      	select e.baseEntityId , max(e.eventDate) eventDate
                      	from event e
                      	where e.eventType = 'Child Home Visit'
                      	group by e.baseEntityId
                      ) e on ec.base_entity_id = e.baseEntityId
                      inner join ec_family_member ef on ec.base_entity_id = ef.base_entity_id and ef.date_removed is null
                      left join (
                      	select re.base_entity_id , STRFTIME('%Y-%m-%d', datetime(max(re.date)/1000,'unixepoch')) last_exclusive_date
                      	from recurring_service_records re
                      	inner join recurring_service_types rt on re.recurring_service_id = rt._id
                      	where rt.type = 'Exclusive_breastfeeding' and ifnull(re.value,'yes') = 'yes'
                      	group by re.base_entity_id
                      ) ex on ex.base_entity_id = e.baseEntityId and SUBSTR(e.eventDate,1,10) between date(ex.last_exclusive_date, '-1 day') and date(ex.last_exclusive_date, '1 day')
                      where (( ifnull(ec.entry_point,'') <> 'PNC' ) or (ifnull(ec.entry_point,'') = 'PNC' and date(ec.dob, '+28 days')  <= date()))
                      and date(ec.dob) between date('now', '-5 month') and date('now') and ex.base_entity_id is null "

  - key: "CHW_012"
    description: "Children (6-23 months) up to date on MNP supplementation"
    indicatorQuery: "select count(distinct alerts.caseID) from alerts where alerts.scheduleName like 'MNP%%' and (alerts.status = 'upcoming' or alerts.status = 'normal')
      and alerts.caseID in (select ec_child.base_entity_id from ec_child where date(ec_child.dob) < date('now', '-6 month') and  date(ec_child.dob) > date('now', '-23 month')
      and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '')"

  - key: "CHW_013"
    description: "Children (6-23 months) overdue for MNP supplementation"
    indicatorQuery: "select count(distinct alerts.caseID) from alerts where alerts.scheduleName like 'MNP%%' and alerts.status = 'urgent'
                           and alerts.caseID in (select ec_child.base_entity_id from ec_child where date(ec_child.dob) < date('now', '-6 month') and  date(ec_child.dob) > date('now', '-23 month')
                           and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '')"

  - key: "CHW_014"
    description: "Children (0-23 months) up to date on immunizations"
    indicatorQuery: "select count(ec_child.base_entity_id) from ec_child where date(ec_child.dob) > date('now', '-24 month')
                                          and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '' and ec_child.base_entity_id not in
                                          (select distinct alerts.caseID from alerts where (alerts.status = 'upcoming' or alerts.status = 'normal' or alerts.status = 'urgent') and alerts.scheduleName
                     					 in ('BCG','OPV 1', 'OPV 2', 'OPV 3', 'PCV 1', 'PCV 2', 'PCV 3', 'Penta 1', 'Penta 2', 'Penta 3', 'Rota 1', 'Rota 2', 'Rota 3', 'MenA', 'Rubella 1', 'Rubella 2', 'IPV', 'YF', 'MCV 1', 'MCV 2'))"

  - key: "CHW_015"
    description: "Children (0-23 months)  who are currently overdue for at least one or more vaccinations"
    indicatorQuery: "select count(ec_child.base_entity_id) from ec_child where date(ec_child.dob) > date('now', '-24 month')
                                          and ifnull(ec_child.dod,'') = '' and ifnull(ec_child.date_removed,'') = '' and ec_child.base_entity_id in
                                          (select distinct alerts.caseID from alerts where alerts.status = 'urgent' and alerts.scheduleName
                     					 in ('BCG','OPV 1', 'OPV 2', 'OPV 3', 'PCV 1', 'PCV 2', 'PCV 3', 'Penta 1', 'Penta 2', 'Penta 3', 'Rota 1', 'Rota 2', 'Rota 3', 'MenA', 'Rubella 1', 'Rubella 2', 'IPV', 'YF', 'MCV 1', 'MCV 2'))"